version: "3.9"

services:
  postgres:
    image: postgres:latest
    container_name: gig_tracker_python_db
    environment:
      POSTGRES_DB: gigtracker_db
      POSTGRES_USER: gigtracker_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
